name: Sync Shadow

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3
      with:
        repository: 'jwergieluk/revllm_shadow'
        path: 'source_repo'
        ref: 'main'

    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: 'jwergieluk/revllm'
        path: 'target_repo'
        ref: 'main'
        token: ${{ secrets.REVLLM_ACCESS_TOKEN }}

    - name: Sync Changes
      run: |
        rm -fr "target_repo/*"
        cp -R source_repo/* target_repo/
        cp source_repo/.gitignore target_repo/

    - name: Commit and Push to Repository B
      run: |
        cd target_repo
        git config --local user.name "jwergieluk"
        git config --local user.email "297652+jwergieluk@users.noreply.github.com"
        git add .
        git commit -m "$(git -C ../source_repo log -1 --pretty=format:%s)"
        git push
